image: python:3.9  # Use an appropriate Python image

stages:
  - lint

before_script:
  - pip install pylint  # Ensure pylint is installed

pylint:
  stage: lint
  script:
    - git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '\.py$' | xargs -r pylint
  only:
    - merge_requests  # Only run this job for merge requests
    - main