image: python:3.9  # Use an appropriate Python image

stages:
  - lint

before_script:
  - pip install pylint  # Ensure pylint is installed

pylint:
  stage: lint
  script:
    - pylint **/*.py  # Run pylint on all Python files in the project
  only:
    - merge_requests  # Only run this job for merge requests
    - main            # Also run on pushes to the main branch
