image: python:3.9  # Use an appropriate Python image

stages:
  - lint

before_script:
  - pip install pylint pylint-exit

pylint:
  stage: lint
  script:
        - echo CI_COMMIT_SHA=${CI_COMMIT_SHA}
        - echo CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
        - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
        - FILES=$(git diff --name-only ${CI_COMMIT_SHA} origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} | grep '\.py'$)
        - echo "Changed files are $FILES"
        - mkdir ./pylint
        - pylint --output-format=text $FILES | tee ./pylint/pylint.log || pylint-exit $?
  only:
    - merge_requests  # Only run this job for merge requests
    - main